;/*FB_PKG_DELIM*/

__d("IGDSDialogFooterPrism.react",["react","react-compiler-runtime"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||d("react");function a(a){var b=d("react-compiler-runtime").c(7),c=a.primary,e=a.secondary;a=a.variant;a=a===void 0?"horizontal":a;var f;b[0]!==e||b[1]!==a?(f={0:{className:"x78zum5"},4:{className:"x78zum5 xtqikln x1szn6h9 xz9dl7a xsag5q8"},2:{className:"x78zum5 x1qjc9v5 xdt5ytf xsag5q8 xz9dl7a"},6:{className:"x78zum5 xtqikln x1szn6h9 x1qjc9v5 xdt5ytf xsag5q8 xz9dl7a"},1:{className:"x78zum5 xp1r0qw"},5:{className:"x78zum5 xtqikln x1szn6h9 xz9dl7a xsag5q8 xp1r0qw"},3:{className:"x78zum5 x1qjc9v5 xdt5ytf xsag5q8 xz9dl7a xp1r0qw"},7:{className:"x78zum5 xtqikln x1szn6h9 x1qjc9v5 xdt5ytf xsag5q8 xz9dl7a xp1r0qw"}}[!!(a==="horizontal")<<2|!!(a==="vertical")<<1|!!(a==="vertical"&&e!=null)<<0],b[0]=e,b[1]=a,b[2]=f):f=b[2];b[3]!==c||b[4]!==e||b[5]!==f?(a=i.jsxs("div",babelHelpers["extends"]({},f,{children:[c,e]})),b[3]=c,b[4]=e,b[5]=f,b[6]=a):a=b[6];return a}g["default"]=a}),98);
__d("Lexical",["cr:370"],(function(a,b,c,d,e,f){e.exports=b("cr:370")}),null);
__d("LexicalComposerContext",["cr:509"],(function(a,b,c,d,e,f){e.exports=b("cr:509")}),null);
__d("LexicalText",["cr:2181"],(function(a,b,c,d,e,f){e.exports=b("cr:2181")}),null);
__d("LexicalUtils",["cr:2774"],(function(a,b,c,d,e,f){e.exports=b("cr:2774")}),null);
__d("MLCHealthLoggerEvent",["$InternalEnum"],(function(a,b,c,d,e,f){a=b("$InternalEnum")({COMMIT_CREATE:"commit_create",COMMIT_EDIT:"commit_edit",DAILY_INTERACTION_WITH_SURFACE:"daily_interaction_with_surface"});c=a;f["default"]=c}),66);
__d("MLCInstrumentationCommands",["Lexical"],(function(a,b,c,d,e,f,g){"use strict";b=(a=d("Lexical")).createCommand();c=a.createCommand();e=a.createCommand();f=a.createCommand();g.COMMIT_COMMAND=b;g.INTERACTION_INSTRUMENTATION_READY=c;g.DOCUMENT_COMMAND=e;g.PLUGIN_EVENT_COMMAND=f}),98);
__d("MlcHealthBizappEventFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("2646");b=d("FalcoLoggerInternal").create("mlc_health_bizapp_event",a);e=b;g["default"]=e}),98);
__d("MlcHealthFacebookAndWorkplaceEventFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("2647");b=d("FalcoLoggerInternal").create("mlc_health_facebook_and_workplace_event",a);e=b;g["default"]=e}),98);
__d("MlcHealthFacebookEventFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("2648");b=d("FalcoLoggerInternal").create("mlc_health_facebook_event",a);e=b;g["default"]=e}),98);
__d("MlcHealthInstagramEventFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("3766");b=d("FalcoLoggerInternal").create("mlc_health_instagram_event",a);e=b;g["default"]=e}),98);
__d("MlcHealthInternalToolsEventFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("2649");b=d("FalcoLoggerInternal").create("mlc_health_internal_tools_event",a);e=b;g["default"]=e}),98);
__d("MlcHealthMessagingLightswitchEventFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("2650");b=d("FalcoLoggerInternal").create("mlc_health_messaging_lightswitch_event",a);e=b;g["default"]=e}),98);
__d("MlcHealthWorkplaceEventFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("2651");b=d("FalcoLoggerInternal").create("mlc_health_workplace_event",a);e=b;g["default"]=e}),98);
__d("MLCHealthInstrumentationPlugin__INTERNAL.react",["Lexical","LexicalComposerContext","LexicalUtils","MLCInstrumentationCommands","MlcHealthBizappEventFalcoEvent","MlcHealthFacebookAndWorkplaceEventFalcoEvent","MlcHealthFacebookEventFalcoEvent","MlcHealthInstagramEventFalcoEvent","MlcHealthInternalToolsEventFalcoEvent","MlcHealthMessagingLightswitchEventFalcoEvent","MlcHealthWorkplaceEventFalcoEvent","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i=(h||d("react")).useLayoutEffect,j=new Set();function k(a){switch(a){case"facebook":return c("MlcHealthFacebookEventFalcoEvent");case"workplace":return c("MlcHealthWorkplaceEventFalcoEvent");case"facebook_and_workplace":return c("MlcHealthFacebookAndWorkplaceEventFalcoEvent");case"internal_tools":return c("MlcHealthInternalToolsEventFalcoEvent");case"messaging_lightswitch":return c("MlcHealthMessagingLightswitchEventFalcoEvent");case"bizapp":return c("MlcHealthBizappEventFalcoEvent");case"instagram":return c("MlcHealthInstagramEventFalcoEvent");default:return null}}function l(a,b,c){(a=k(a))==null||a.log(function(){return{event:c,surface:b}})}function a(a){var b=a.policyProduct,c=a.surface;a=d("LexicalComposerContext").useLexicalComposerContext();var e=a[0];i(function(){var a=function(){};j.has(c)||(a=e.registerUpdateListener(function(d){var f=d.dirtyLeaves;d=d.tags;if(j.has(c)){a();return}if(f.size===0||d.has("history-merge")||!e.isEditable())return;j.add(c);l(b,c,"daily_interaction_with_surface");a()}));return d("LexicalUtils").mergeRegister(a,e.registerCommand(d("MLCInstrumentationCommands").COMMIT_COMMAND,function(a){a==="create"?l(b,c,"commit_create"):l(b,c,"commit_edit");return!1},d("Lexical").COMMAND_PRIORITY_CRITICAL))},[e,b,c]);return null}g["default"]=a}),98);
__d("MLCInteractionInstrumentationPlugin__INTERNAL.react",["cr:3286","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||d("react");function a(a){return b("cr:3286")&&i.jsx(b("cr:3286"),babelHelpers["extends"]({},a))}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("MLCTextLengthBucket",["$InternalEnum"],(function(a,b,c,d,e,f){"use strict";var g=b("$InternalEnum").Mirrored(["S","M","L","XL"]);function a(a){if(a<=500)return g.S;if(a<=1e3)return g.M;return a<=2500?g.L:g.XL}f.TextLengthBucketEnum=g;f.getTextLengthBucket=a}),66);
__d("mlcInternBootstrapTypingPerformance__INTERNAL",["OneTraceQPLLogger","one-trace","qpl"],(function(a,b,c,d,e,f,g){"use strict";var h=!1;function i(a){switch(a.traceType){case"TYPING":return c("qpl")._(406397789,"516")}return null}function a(){h||(h=!0,c("one-trace").subscribe("trace-start",function(a){d("OneTraceQPLLogger").initQPL(i(a),a)}),c("one-trace").subscribe("trace-end",function(a){d("OneTraceQPLLogger").logQPL(i(a),a)}))}g["default"]=a}),98);
__d("MLCTypingPerformancePlugin__INTERNAL.react",["LexicalComposerContext","LexicalText","MLCTextLengthBucket","mlcInternBootstrapTypingPerformance__INTERNAL","one-trace","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||(h=d("react")),j=h.useLayoutEffect,k=new RegExp("[^,;\\s]{200,}"),l=new RegExp("[^,;\\s]{100,199}"),m=new RegExp("[^,;\\s]{50,99}");function n(a){if(a==="")return 0;if(k.test(a))return 200;else if(l.test(a))return 100;else if(m.test(a))return 50;else return 0}function a(a){c("mlcInternBootstrapTypingPerformance__INTERNAL")();return i.jsx(o,babelHelpers["extends"]({},a))}a.displayName=a.name+" [from "+f.id+"]";function o(a){var b=a.format__DEPRECATED,e=a.surface;a=a.typingPerformanceID;var f=a===void 0?"":a;a=d("LexicalComposerContext").useLexicalComposerContext();var g=a[0];j(function(){var a=babelHelpers["extends"]({largeWord:n(g.getEditorState().read(d("LexicalText").$rootTextContent)),textLengthBucket:d("MLCTextLengthBucket").getTextLengthBucket(g.getEditorState().read(d("LexicalText").$rootTextContent).length)},e==="FeedComposerCometStatusArea"?{autolinkFastPath:String(!0)}:null),h;i();function i(){h==null||h();var d=null,i=g.registerRootListener(function(g){if(g===d)return;d!==null&&c("one-trace").unregisterTypingPerf(d);g!==null&&c("one-trace").trackTypingPerf(g,e,d,babelHelpers["extends"]({},a,{editor:"LexicalEditor",format:b!=null?b:"",typingPerformanceID:f}));d=g});h=function(){i(),d!==null&&c("one-trace").unregisterTypingPerf(d)}}var j=g.registerTextContentListener(function(b){b=n(b);b!==a.largeWord&&(a.largeWord=b,i())}),k=g.registerTextContentListener(function(b){b=d("MLCTextLengthBucket").getTextLengthBucket(b.length);b!==a.textLengthBucket&&(a.textLengthBucket=b,i())});return function(){h==null||h(),j==null||j(),k==null||k()}},[f,g,b,e]);return null}o.displayName=o.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("MLCInstrumentationPlugin__INTERNAL.react",["MLCHealthInstrumentationPlugin__INTERNAL.react","MLCInteractionInstrumentationPlugin__INTERNAL.react","MLCTypingPerformancePlugin__INTERNAL.react","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||d("react");b="facebook";b;function a(a){return i.jsxs(i.Fragment,{children:[i.jsx(c("MLCTypingPerformancePlugin__INTERNAL.react"),babelHelpers["extends"]({},a)),i.jsx(c("MLCHealthInstrumentationPlugin__INTERNAL.react"),babelHelpers["extends"]({},a)),i.jsx(c("MLCInteractionInstrumentationPlugin__INTERNAL.react"),babelHelpers["extends"]({},a))]})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("PolarisChallengeRoot.entrypoint",["JSResourceForInteraction"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){return{queries:{}}},root:c("JSResourceForInteraction")("PolarisChallengeRoot.react").__setRef("PolarisChallengeRoot.entrypoint")};g["default"]=a}),98);